# @summary custom datatype for Build entries of podman build quadlet
# @see https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html
type Quadlets::Unit::Build = Struct[
  Optional['Annotation']            => Variant[Array[String[1],1], String[1]],
  Optional['Arch']                  => String[1],
  Optional['AuthFile']              => Stdlib::Unixpath,
  Optional['BuildArg']              => Variant[Array[String[1],1], String[1]],
  Optional['ContainersConfModule']  => Variant[Array[String[1],1], String[1]],
  Optional['DNS']                   => Variant[Array[Stdlib::IP::Address,1], Stdlib::IP::Address],
  Optional['DNSOption']             => Variant[Array[String[1],1], String[1]],
  Optional['DNSSearch']             => Variant[Array[Stdlib::Fqdn,1], Stdlib::Fqdn],
  Optional['Environment']           => Variant[Array[String[1],1], String[1]],
  Optional['File']                  => String[1],
  Optional['ForceRM']               => Boolean,
  Optional['GlobalArgs']            => Variant[Array[String[1],1], String[1]],
  Optional['GroupAdd']              => Variant[Array[String[1],1], String[1]],
  Optional['IgnoreFile']            => Stdlib::Unixpath,
  Optional['ImageTag']              => Variant[Array[String], String],
  Optional['Label']                 => Variant[Array[String[1],1], String[1]],
  Optional['Network']               => Variant[Array[String[1],1], String[1]],
  Optional['PodmanArgs']            => Variant[Array[String[1],1], String[1]],
  Optional['Pull']                  => Enum['always','missing','never','newer'],
  Optional['Retry']                 => Integer[0],
  Optional['RetryDelay']            => String[1],
  Optional['Secret']                => Variant[Array[String[1],1], String[1]],
  Optional['SetWorkingDirectory']   => String[1],
  Optional['Target']                => String[1],
  Optional['TLSVerify']             => Boolean,
  Optional['Variant']               => String[1],
  Optional['Volume']                => Variant[Array[String[1],1], String[1]],
]
